runtime: python39
service: default
env: standard

entrypoint: gunicorn -b :$PORT payfast.wsgi:application

runtime_config:
  python_version: 3.9

env_variables:
  DJANGO_SETTINGS_MODULE: 'payfast.settings'
  DEBUG: 'False'
  GCP_PROJECT: 'your-project-id'

handlers:
- url: /static
  static_dir: static/
  secure: always

- url: /media
  static_dir: media/
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: 'your-project:region:instance-name'